### ISSUE TITLE
validate uploaded server configuration to ensure proper syntax 

### ISSUE THREAD

**Issue by codyseibert** [codyseibert/fire-stone-hosting#17]

**Comment by Arturo-Lopez** [comment]
A object validation lib like [yup](https://github.com/jquense/yup) can be use and it also gives feedback for the client in case the validation fails

**Comment by Arturo-Lopez** [comment]
@codyseibert  Is there any configuration value that must not be allowed to be changed?

**Comment by codyseibert** [comment]
@Arturo-Lopez maybe port related ones?  Maybe just make a configurable blacklist or whitelist so we can pick and choose what is allowed to change.  Are you planning to work on this one?

**Comment by Arturo-Lopez** [comment]
@codyseibert That sounds appropriate and yes I plan to work on the problem
