### ISSUE TITLE
Issue while running npm start.

### ISSUE THREAD

**Issue by KendallDoesCoding** [codyseibert/fire-stone-hosting#35]
I opened LandingPage.tsx in chrome, and I cannot see what you saw, I can only see the code written. Please help

**Comment by codyseibert** [comment]
@KendallDoesCoding you need to actually host the client by using `cd client && npm run start`.  Again, this application was created using create-react-app.  Once it's running, you can go to http://localhost:3000

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding you need to actually host the client by using `cd client && npm run start`. Again, this application was created using create-react-app. Once it's running, you can go to http://localhost:3000

I have a pc and laptop issue with npm, can you host it on vercel like I requested, they have to option to make it a create-react-app. I'll link a repo that did it if you need it!

**Comment by codyseibert** [comment]
@KendallDoesCoding sorry to be blunt, but could you please just fix your npm issues?

**Comment by KendallDoesCoding** [comment]
Yes. I'm working on that, Sorry for the inconvenience.

**Comment by KendallDoesCoding** [comment]
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@8.1.4
2 info using node@v17.2.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\Admin\Downloads\fire-stone-hosting-master\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Admin\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Admin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 3ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 24ms
27 timing command:run-script Completed in 15ms
28 timing command:start Completed in 187ms
29 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Admin\Downloads\fire-stone-hosting-master\package.json'
30 verbose cwd C:\Users\Admin\Downloads\fire-stone-hosting-master
31 verbose Windows_NT 10.0.19044
32 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
33 verbose node v17.2.0
34 verbose npm  v8.1.4
35 error code ENOENT
36 error syscall open
37 error path C:\Users\Admin\Downloads\fire-stone-hosting-master/package.json
38 error errno -4058
39 error enoent ENOENT: no such file or directory, open 'C:\Users\Admin\Downloads\fire-stone-hosting-master\package.json'
40 error enoent This is related to npm not being able to find a file.
41 verbose exit -4058

**Comment by KendallDoesCoding** [comment]
@codyseibert Here's the issue, do you know what the problem is?

**Comment by codyseibert** [comment]
@KendallDoesCoding you need to `cd client` and run `npm i` first.  It looks like you are running npm commands from the root of the project.  The readme.md outlines how you can run this project.

**Comment by KendallDoesCoding** [comment]
Thanks, sorry for asking stupid questions, I just haven't run node or react
before.

**Comment by KendallDoesCoding** [comment]
Another stupid question, but I'm getting this error, what do I need to
replace the && with?

At line:1 char:11
+ cd client && npm i && npm start
+           ~~
The token '&&' is not a valid statement separator
in this version.
At line:1 char:20
+ cd client && npm i && npm start
+                    ~~
The token '&&' is not a valid statement separator
in this version.
    + CategoryInfo          : ParserError: (:) [],
   ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

**Comment by KendallDoesCoding** [comment]
Trying to run npm, will reopen if get another issue.

**Comment by KendallDoesCoding** [comment]
@codyseibert It's giving me options, but if I tap it doesn't do anything, I can't type anything too.

> client@0.1.0 start
> react-scripts start

**Comment by codyseibert** [comment]
@KendallDoesCoding what do you mean by options?  you should just be able to run it, and then open your browser to http://localhost:3000 when it's ready

**Comment by KendallDoesCoding** [comment]
I'm getting those options and if I type 1 or 2 it gives me this error.

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10) 
    at iterateNormalLoaders (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10) 
C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Admin\Downloads\fire-stone-hosting-master\client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0

**Comment by KendallDoesCoding** [comment]
![image](https://user-images.githubusercontent.com/84712013/145865197-67953e14-1a68-4e0e-9ddb-09199b03d051.png)
![image](https://user-images.githubusercontent.com/84712013/145865243-dcf53fc0-e05e-405c-98e9-ab921d918d2e.png)

**Comment by Arturo-Lopez** [comment]
> ![image](https://user-images.githubusercontent.com/84712013/145865197-67953e14-1a68-4e0e-9ddb-09199b03d051.png) ![image](https://user-images.githubusercontent.com/84712013/145865243-dcf53fc0-e05e-405c-98e9-ab921d918d2e.png)

@KendallDoesCoding  Try using a LTS version of Node it looks an issue of that nature, maybe with v14.x or v16.x. It works properly on v14.x

**Comment by KendallDoesCoding** [comment]
Ok, I'll do that!

**Comment by codyseibert** [comment]
@KendallDoesCoding did you get it running?

**Comment by KendallDoesCoding** [comment]
No, not yet!

**Comment by KendallDoesCoding** [comment]
> > ![image](https://user-images.githubusercontent.com/84712013/145865197-67953e14-1a68-4e0e-9ddb-09199b03d051.png) ![image](https://user-images.githubusercontent.com/84712013/145865243-dcf53fc0-e05e-405c-98e9-ab921d918d2e.png)
> 
> @KendallDoesCoding Try using a LTS version of Node it looks an issue of that nature, maybe with v14.x or v16.x. It works properly in both of those versions

Can I download v16.13.1? Will it work there @Arturo-Lopez ?

**Comment by KendallDoesCoding** [comment]
@codyseibert for now can you upload the files to vercel, idk how to but if you figure out that would be very helpful for now, don't link it to the repo, just dm me the url. Thanks
https://vercel.com/

**Comment by KendallDoesCoding** [comment]
@Arturo-Lopez I have installed the LTS version as you requested, and I am running the old version of this project. I am currently running npm i.

**Comment by KendallDoesCoding** [comment]
Nope, it seems to be the same issue. I am getting the options. Let me try the updated version of this project.

**Comment by KendallDoesCoding** [comment]
Closing in favour of:

1. Update
2. #73
