### ISSUE TITLE
Apply a monorepo tool

### ISSUE THREAD

**Issue by Arturo-Lopez** [codyseibert/fire-stone-hosting#40]
### Describe the feature or problem you’d like to solve
Using a monorepo tool would allow share configs and code much easier and also simplify dev and build experience

### Proposed solution
Some projects that allows this are:
- yarn workspaces: It's base on `yarn` package manager and simplifies the task of sharing code. [Demo link](https://youtu.be/G8KXFWftCg0)
-  Turborepo: Is a blazing fast build system for JavaScript/TypeScript monorepos codebases containing multiple projects, often using multiple frameworks, in a single unified code repository (Docs description). [Demo link](https://youtu.be/YX5yoApjI3M)
- Lerna: It's usually the tool to go in a lot a of monorepo projects. [Demo link](https://youtu.be/ZSdCNf1ncOE)

### Additional context
The following video resumes the above content. [Link](https://youtu.be/9iU_IE6vnJ8)

**Comment by codyseibert** [comment]
This sounds fine to me.  Pick whatever tool you think is best.  I'd personally want to learn more about Lerna since a lot of other people use it.  Any clue why these issues are automatically getting assigned to me?  If you plan to work on this, please assign it to yourself.

**Comment by Arturo-Lopez** [comment]
Lerna is very cool but also Turborepo is very interesting. You may need to edit the github action and I think I can't assign my self or put labels

**Comment by Arturo-Lopez** [comment]
> This sounds fine to me. Pick whatever tool you think is best. I'd personally want to learn more about Lerna since a lot of other people use it. Any clue why these issues are automatically getting assigned to me? If you plan to work on this, please assign it to yourself.

Lerna is very cool but also Turborepo is very interesting. You may need to edit the github action and I think I can't assign my self or put labels

**Comment by KendallDoesCoding** [comment]
> This sounds fine to me. Pick whatever tool you think is best. I'd personally want to learn more about Lerna since a lot of other people use it. Any clue why these issues are automatically getting assigned to me? If you plan to work on this, please assign it to yourself.

I set it in the template to auto-assign it to you. I can remove that if you don't like it doing that!

**Comment by codyseibert** [comment]
As long as Turborepo doesn't tied us into Vercel.  I don't plan to use vercel, so I'd rather use yarn or npm workspaces if it is a simpler solution.

**Comment by Arturo-Lopez** [comment]
@codyseibert For now I also think is sufficient to rely on one of those package manager, the other tools come handy in more complex workflows
