### ISSUE TITLE
Add "build" and "start build"  commands for api and agent

### ISSUE THREAD

**Issue by Arturo-Lopez** [codyseibert/fire-stone-hosting#41]
### Describe the feature or problem you’d like to solve
Create a `build` and `start build` command for api and agent

### Proposed solution
This would allow easier deploying with the following commands
- build: For creating production code
- start: For running production code
- dev (rename from start): For running dev server 

### Additional context
Maybe refactor the current 'start' command to 'dev' would be an option but I need opinions

**Comment by codyseibert** [comment]
This sounds fine to me.  Any clue why these issues are automatically getting assigned to me?  If you plan to work on this, please assign it to yourself.

**Comment by KendallDoesCoding** [comment]
> This sounds fine to me. Any clue why these issues are automatically getting assigned to me? If you plan to work on this, please assign it to yourself.

I set it in the template to auto-assign it to you. I can remove that if you don't like it doing that!, Sorry...
