### ISSUE TITLE
Ability to choose a MC Version

### ISSUE THREAD

**Issue by codyseibert** [codyseibert/fire-stone-hosting#56]
### Describe the feature or problem you’d like to solve
Give users the ability to choose from 2 different MC versions when they initially rent the server

**Comment by KendallDoesCoding** [comment]
> ### Describe the feature or problem you’d like to solve
> Give users the ability to choose from 2 different MC versions when they initially rent the server

This is a really good idea!

**Comment by Arturo-Lopez** [comment]
This is a interesting issue so I have made some research my self and I have the following

### How to get any version available

I have found [this question](https://gaming.stackexchange.com/questions/123194/is-there-a-way-to-get-the-latest-server-jar-through-a-url-that-doesnt-change) which describes form which endpoint the current launcher gets all the availables versions

`https://launchermeta.mojang.com/mc/game/version_manifest.json` 

As describe in the question from above you can get any version and most important its respective `server.jar` of each given version

```json
{
  "latest": {
      "release": "1.18.1",
      "snapshot": "1.18.1"
  },
  "versions": [
      {
          "id": "1.18.1",
          "type": "release",
          "url": "https://launchermeta.mojang.com/v1/packages/b0bdc637e4c4cbf0501500cbaad5a757b04848ed/1.18.1.json",
          "time": "2021-12-10T08:26:34+00:00",
          "releaseTime": "2021-12-10T08:23:00+00:00"
      }
    ]
}
```

```json
{
  "downloads": {
      "client": {
          "sha1": "7e46fb47609401970e2818989fa584fd467cd036",
          "size": 20042090,
          "url": "https://launcher.mojang.com/v1/objects/7e46fb47609401970e2818989fa584fd467cd036/client.jar"
      },
      "client_mappings": {
          "sha1": "99ade839eacf69b8bed88c91bd70ca660aee47bb",
          "size": 6611464,
          "url": "https://launcher.mojang.com/v1/objects/99ade839eacf69b8bed88c91bd70ca660aee47bb/client.txt"
      },
      "server": {
          "sha1": "125e5adf40c659fd3bce3e66e67a16bb49ecc1b9",
          "size": 46324407,
          "url": "https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar"
      },
      "server_mappings": {
          "sha1": "9717df2acd926bd4a9a7b2ce5f981bb7e4f7f04a",
          "size": 5115621,
          "url": "https://launcher.mojang.com/v1/objects/9717df2acd926bd4a9a7b2ce5f981bb7e4f7f04a/server.txt"
      }
  }
}
```

### Deploy any selected version

To get to this step I was thinking the following 
- Save the version of each server in the DB and maybe other properties
- Implement a custom flow for building images given a specific version 
- Manage a central registry from where you can fetch a pre-build image of each version given a specific version tag (this is thinking for a deployment perspective)

**Comment by codyseibert** [comment]
@Arturo-Lopez interesting find with that manifest.json.  I'm currently working on a basic implementation, but I did have in mind using a custom registry with pre-built images to speed up deploy times and to reduce the need to run docker build on the agents.

**Comment by Arturo-Lopez** [comment]
@codyseibert That's a really cool project it saves you a lot of time and looks like the way to go

**Comment by codyseibert** [comment]
The initial work is setup for this, closing
