### ISSUE TITLE
[Bug]: (Install workspace error)

### ISSUE THREAD

**Issue by KendallDoesCoding** [codyseibert/fire-stone-hosting#73]
### Describe the bug
Write a clear and concise description of what the bug is.

### Steps to reproduce the behavior

1. Go to 'terminal'
2. Run 'install-workspace'

### Expected behavior

Idk what's wrong

### Actual behavior

Idk what's wrong

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Output

PS C:\Users\Admin\Downloads\fire-stone-hosting-master (1)> install-workspace
install-workspace : The term 'install-workspace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ install-workspace
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (install-workspace:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Arturo-Lopez** [comment]
@KendallDoesCoding  I think you are just trying to run `install-workspace` instead of `npm run install-workspace`

**Comment by KendallDoesCoding** [comment]
Yes

**Comment by KendallDoesCoding** [comment]
@Arturo-Lopez , @codyseibert Getting this error when I run npm run install-workspace

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'install-workspace'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\Admin\Downloads\fire-stone-hosting-master (1)\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Admin\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\Admin\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 20ms
27 timing command:run-script Completed in 2ms
28 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Admin\Downloads\fire-stone-hosting-master (1)\package.json'
29 verbose cwd C:\Users\Admin\Downloads\fire-stone-hosting-master (1)
30 verbose Windows_NT 10.0.19044
31 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install-workspace"
32 verbose node v16.13.1
33 verbose npm  v8.1.2
34 error code ENOENT
35 error syscall open
36 error path C:\Users\Admin\Downloads\fire-stone-hosting-master (1)/package.json
37 error errno -4058
38 error enoent ENOENT: no such file or directory, open 'C:\Users\Admin\Downloads\fire-stone-hosting-master (1)\package.json'
39 error enoent This is related to npm not being able to find a file.
40 verbose exit -4058

**Comment by Arturo-Lopez** [comment]
@KendallDoesCoding Can you try with lastest commit? delete all `node_modules` in your project folder and then run `npm run install-workspace` in the root folder

**Comment by codyseibert** [comment]
I had no issues installing deps

**Comment by KendallDoesCoding** [comment]
> I had no issues installing deps

Yeah, its just my laptop and pc ig.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Can you try with lastest commit? delete all `node_modules` in your project folder and then run `npm run install-workspace` in the root folder

Thanks, Will do this later in the day.

**Comment by codyseibert** [comment]
this sounds like an issue specific to your machine, closing

**Comment by KendallDoesCoding** [comment]
Yes. That's true...And you guys gave me the help I needed, just gotten
around to doing it yet.

**Comment by KendallDoesCoding** [comment]
@codyseibert It gave me the options in gitpod too, but it worked!!!
